spring:
  main:
    log-startup-info: true
    banner-mode: off
    output.ansi.enabled: ALWAYS
  sql:
    init:
      mode: ALWAYS
      schema-locations: classpath:schema.sql
      data-locations: classpath:data.sql
    datasource:

      url: jdbc:h2:file:./db/filmorate
      driverClassName: org.h2.Driver
      username: sa
      password: password

logging.level:
  org.zalando.logbook: DEBUG
  ru.yandex.practicum.filmorate: DEBUG